### ISSUE TITLE
intro don't support react-dom

### ISSUE THREAD

**Issue by ql434** [HiDeoo/intro.js-react#1]
![image](https://user-images.githubusercontent.com/7567247/28353403-2d70e64c-6c8e-11e7-8bac-e591efb4e0b9.png)

**Comment by HiDeoo** [comment]
Thanks for your feedback.

Indeed, as stated in [the documentation](https://github.com/HiDeoo/intro.js-react#step), the `intro` property is currently only accepting a `string` for the tooltip text.

I'm a bit short on time currently so I'm not planning to add new features or extend the functionalities but I would be happy to review and consider any pull request.
