### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by JasonSooter** [HiDeoo/intro.js-react#10]
Has anyone used this with React > 16? Changing the packages in the CodeSandbox showed no issues.

**Comment by HiDeoo** [comment]
Yeah, I've been using it with React 16 without any issue.

For sanity, I just pushed an [updated `peerDependencies`](https://github.com/HiDeoo/intro.js-react/commit/7765beea328408fd0eae3e7126aa00a6726bbbb4) to support React 16 and not get any warning during installation.

I'm still hesitant to release `0.2.0` tho as it contains breaking changes to support a new feature of an alpha version and the latest `intro.js` published version is still `2.8.0-alpha.1`...

**Comment by JasonSooter** [comment]
@HiDeoo Ok good to know. Thanks for the reply. I've not had any issues using 16 either. I'll let you know if I do.
