### ISSUE TITLE
Previous button not visible when there is only one step in tutorial

### ISSUE THREAD

**Issue by disha1202** [HiDeoo/intro.js-react#103]
### Describe the bug

Previous button not visible when there is only one step in tutorial

![Screenshot from 2023-03-02 12-09-44](https://user-images.githubusercontent.com/58461801/222351662-4cb68299-4d09-4d2b-a5b3-e8f177e727f3.png)

Works fine in case of multiple steps

![Screenshot from 2023-03-02 12-15-55](https://user-images.githubusercontent.com/58461801/222351865-018c85df-6c22-43e9-90d1-583360aebf9b.png)

         

### To Reproduce

         `<Steps
			  enabled={true}
                          steps={tutorialSteps(this.props.pathname, this.props.intl)}
			  options={{
				"nextLabel": this.props.intl.formatMessage({ id: NEXT_SHORT }),
				"prevLabel": this.props.intl.formatMessage({ id: PREV }),
				"exitOnOverlayClick": false,
                                "nextToDone": false,
				"showBullets": false,
				"tooltipClass": 'customTooltip',
				"hidePrev": false
			  }}
			  initialStep= {0}
			  onExit= {() => {this.props.unmount();
				console.log(tutorialSteps(this.props.pathname, this.props.intl))
			  }}
            />`

### Expected behavior

The prev button should be visible in case there is only one step

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report. Unfortunately, this seems to be a behavior hardcoded in intro.js itself:

https://github.com/usablica/intro.js/blob/81f8efbf984f12cece9a5c48cff0a63e2c6d9428/src/core/showElement.js#L457-L460

Maybe this could be workaround by adding a fake step that is never shown to the user, or something like that but I guess the proper way would be to have an option for this directly in intro.js.
