### ISSUE TITLE
How can i added delay for prevent this bugs?

### ISSUE THREAD

**Issue by Farhatdjehan** [HiDeoo/intro.js-react#107]
### Describe the bug

![image](https://github.com/HiDeoo/intro.js-react/assets/58970118/ca602cd0-6797-4268-9b41-6f86dadd7744)

i use nextjs v12 and then want to highlight the other element at the bottom.. but the element not ready yet to highlight.. is there any solution?

### To Reproduce

1. Add step
2. Add highlight element at the bottom

### Expected behavior

add delay for waiting my element ready

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
You can check the [_dynamic elements_ section](https://github.com/HiDeoo/intro.js-react#dynamic-elements) of the README for this specific case.

Basically, when your element becomes ready, you can use the `updateStepElement()` to update the element associated to a specific step.

For more details, you can also check [the PR](https://github.com/HiDeoo/intro.js-react/pull/4) that implemented this feature and I also found [this old example](https://codesandbox.io/s/introjs-react-dynamic-element-example-bk6xj) using this API to use a dynamically added element for the step 3.
