### ISSUE TITLE
Allow multi route

### ISSUE THREAD

**Issue by VishnuJangid8955** [HiDeoo/intro.js-react#111]
### Is your feature request related to a problem?

This is a problem. Because if I want to show the intro for multiple routes this is not allowing me for that.

### Describe the solution you'd like

We can give a feature to allow multiple routes as other npm have the same. We can take the route as a parameter and redirect to that and after that, we will show the tooltip to the user.

**Comment by HiDeoo** [comment]
Thanks for your issue.

This seems to be out of the scope of the project. This wrapper provides quite a few [callbacks and options](https://github.com/HiDeoo/intro.js-react#props), e.g `onBeforeChange` called before changing the current step, to customize the behavior of your steps. You can use them to describe behavior like "when the user clicks on the _Next_ button of the last step on this page, navigate to the next page which will continue the tour". Of course, how you navigate to the next page is up to you and the framework/libraries you are using.

**Comment by VishnuJangid8955** [comment]
Thanks!
But I found a way to do multi-routing when I checked other npm similar to this. They are using context for multi-routing, the same thing I'm doing in my project.
