### ISSUE TITLE
Allow to change current step

### ISSUE THREAD

**Issue by VishnuJangid8955** [HiDeoo/intro.js-react#112]
### Is your feature request related to a problem?

If the developer wants to change the current step from 2 to 5 then. They are not able to change that.

### Describe the solution you'd like

We can give a setCurrentStep feature so the user can change the current step. the

**Comment by HiDeoo** [comment]
Thanks for your report.

The [Intro.js API](https://introjs.com/docs) provides a [`goToStep()`](https://introjs.com/docs/intro/api#introjsgotostepstep) function for such use cases. When using this wrapper, you can still access the Intro.js instance by using a ref on either the `<Steps />` or `<Hints />` components as documented [here](https://github.com/HiDeoo/intro.js-react#introjs-api).

**Comment by VishnuJangid8955** [comment]
I'm getting an error when I'm using ref. Please check

<img width="1012" alt="Screenshot 2024-03-29 at 10 22 19 PM" src="https://github.com/HiDeoo/intro.js-react/assets/47751902/3aa06616-bf3f-46e3-8ab7-2550c82db62c">
