### ISSUE TITLE
React native Support 

### ISSUE THREAD

**Issue by geneshairzan** [HiDeoo/intro.js-react#116]
### Is your feature request related to a problem?

Hi, ist this library support for react native  ?

### Describe the solution you'd like

its kinda cool if this library support react native

**Comment by HiDeoo** [comment]
Thanks for your feature request.

Unfortunately, this library is just a wrapper for React around the [`intro.js`](https://introjs.com/) library which heavily use the DOM which would not be available in a React Native environment. Support for React Native would require having `intro.js` to be compatible with React Native. There is a [feature request](https://github.com/usablica/intro.js/issues/658) for this in the `intro.js` repository but nothing can be done in this repository to add such support.
