### ISSUE TITLE
The `position` attribute isn't working

### ISSUE THREAD

**Issue by zoheiry** [HiDeoo/intro.js-react#15]
I have a step that looks as follows
```
{
  element: ".elemntClassName",
  intro: "Hello world",
  position: "top"
}
```
It never shows up on top, I've tried all the different placements, but nothing seems to be changing it from bottom.

**Comment by HiDeoo** [comment]
Hi,

I can't seem to repro this issue. I tried with a step similar to you:

```js
{
  element: '.test1',
  intro: 'test 1',
  position: 'left',
}
```

It'll render properly to the left:

<img width="488" alt="screen shot 2018-03-12 at 17 18 08" src="https://user-images.githubusercontent.com/494699/37295909-b6a75d02-2619-11e8-90ae-f189e79683ad.png">

Please note that `intro.js` will make sure it has room to render the step, for example, if my `test1` div is positioned on the left side of my page without any room to render the step, it'll default to another side. For example, with the same step with `left` position, it'll render on the right no matter what:

<img width="484" alt="screen shot 2018-03-12 at 17 18 22" src="https://user-images.githubusercontent.com/494699/37295999-f8e7d566-2619-11e8-8d1e-cc7426afaa9c.png">

I don't know how `intro.js` actually calculate that, you may need to check their source code if you need more details regarding that part.

I'll close the issue at the moment as I can't repro but make sure to re-open if you can provide a repro.

**Comment by zoheiry** [comment]
@HiDeoo Could you also try `bottom-right-aligned` because that seems to be the one that isn't working.

**Comment by zoheiry** [comment]
After a bit of digging I found the issue in IntroJs, I'm attempting to fix it, and will create a PR from them. Thanks for your help 👍

**Comment by webdevbry** [comment]
Any fix for this? I'm having this happen in Intro 4.3.0
