### ISSUE TITLE
How to attach a step/hint to a sub menu item inside a dropdown menu

### ISSUE THREAD

**Issue by BruceL33t** [HiDeoo/intro.js-react#16]
As the title says, imagine you wanted to attach a step/hint to a submenu item in a navigation menu that only reveals sub menu items when you hover over the top level items.

Is that possible to do with this library as it stands right now? Or would it be an idea to add a "nextElement" (a reference to the DOM element) from which you could get the parent and call .show on or something?

**Comment by HiDeoo** [comment]
Hi,

I guess depending on your menu implementation, things could vary but my first approach would be to simply use the `enabled` prop available in both components (`<Steps />` & `<Hints />`) and have it saved in a state somewhere.

I would implement in my menu some callbacks like `submenuDidBecomeVisible`, `onVisible` or something like that in which I could update my state containing the `enabled` value which will show / hide the steps or hints when necessary.

I'm not quite sure I get the whole `nextElement` idea yet but feel free to re-open the issue with more details if needed or open a PR altho I'm not sure yet if this should be in the scope of this library.

**Comment by ArwaTawfik** [comment]
if anyone has a solution for this problem I will really appreciate it
