### ISSUE TITLE
Why can't I update the options after mounting the component

### ISSUE THREAD

**Issue by zoheiry** [HiDeoo/intro.js-react#17]
I have my render method as follows
```
render() {
  options = {
    disableInteraction: this.state.disableInteraction,
    ...,
  }
  <Steps 
    options={options}
    ...
  />
}
```

When the state updates `disableInteraction` introJs doesn't update. Is this intentional, and is there a way around it?

**Comment by HiDeoo** [comment]
I can't seem to repro.

I've forked the project demo on codesandbox.io & updated it to use options stored in the state. The `Toggle Progress` button seems to update the options just fine.

https://codesandbox.io/s/p9o9jr98m?hidenavigation=1

If this is still an issue, feel free to re-open with a repro.

**Comment by zoheiry** [comment]
Here's the repro 
https://codesandbox.io/s/7yvr1knk9x
In the `onBeforeChange` I am updating the options, but it's not reflecting in the actual intro

**Comment by HiDeoo** [comment]
I see, you're not toggling visibility and are using `onbeforechange`. This is indeed intended to get the same current behavior as intro.js `setOption` & `setOptions` APIs.

If I remember correctly, they have open issues about this as it's currently not supported but should be in future versions so when this works in `intro.js`, this should work automatically in this wrapper (if they don't change the API).

**Comment by zoheiry** [comment]
Is there any workaround now to update the options mid tutorial? or do I have to wait for introJs to fix their issue?

**Comment by HiDeoo** [comment]
Depending on what options you need to change, I would, until they provide a better API, just reproduce what they're doing internally, for example to update the `nextLabel` option, you could:

```js
if (nextStepIndex === 4) {
  document.querySelector('.introjs-nextbutton').innerHTML = 'something else'
} else {
  document.querySelector('.introjs-nextbutton').innerHTML = 'Next'
}
```

I don't know what they're doing exactly for `disableInteraction` but that should be easily to find in their source code.

**Comment by zoheiry** [comment]
Alright, I'll check it out, thanks 👍

**Comment by namlq93** [comment]
> Depending on what options you need to change, I would, until they provide a better API, just reproduce what they're doing internally, for example to update the `nextLabel` option, you could:
> 
> ```js
> if (nextStepIndex === 4) {
>   document.querySelector('.introjs-nextbutton').innerHTML = 'something else'
> } else {
>   document.querySelector('.introjs-nextbutton').innerHTML = 'Next'
> }
> ```
> 
> I don't know what they're doing exactly for `disableInteraction` but that should be easily to find in their source code.

I only want to hide the number in `introjs-helperNumberLayer`, I used to `$(".introjs-helperNumberLayer")[0].innerHTML = ''` or `$('.introjs-helperNumberLayer').empty()` but it is not working. 

```
.onbeforechange(function () {
    $( document ).ready(function() {
        if(intro._currentStep === 1) {
            $(".introjs-helperNumberLayer")[0].innerHTML = ''
        }
    })
})
```

Here's what I expected:
![Screen Shot 2021-04-29 at 13 54 54](https://user-images.githubusercontent.com/41458989/116512632-8d3bf180-a8f2-11eb-970f-acd8149ba97e.png)
