### ISSUE TITLE
how to change button text

### ISSUE THREAD

**Issue by AntoninSorrento** [HiDeoo/intro.js-react#19]
**### use**
![image](https://user-images.githubusercontent.com/26902024/41947932-fe99e8d8-79ec-11e8-9772-ed9f3475eede.png)
![image](https://user-images.githubusercontent.com/26902024/41947938-0967cafa-79ed-11e8-8f06-a40ad5aac96f.png)
**### will be**
text no change

**Comment by HiDeoo** [comment]
The `nextLabel`, `prevLabel` & `skipLabel` options are [Intro.js options](https://github.com/HiDeoo/intro.js-react#introjs-options) which can be passed down using the `options` prop.

For example, the following code:

```js
<Steps
  enabled={stepsEnabled}
  steps={steps}
  initialStep={initialStep}
  onExit={this.onExit}
  options={{
    nextLabel: 'test next',
    prevLabel: 'test previous',
    skipLabel: 'test skip'
  }}
/>
```

Will give you this output:

![screen shot 2018-06-27 at 15 48 59](https://user-images.githubusercontent.com/494699/41978371-ff284558-7a21-11e8-8394-22c33211ad8d.png)

The available Step options are described [here](https://github.com/HiDeoo/intro.js-react#step).

**Comment by AntoninSorrento** [comment]
thanks a lot
