### ISSUE TITLE
 i can't import files intro.js-react and introjs.css

### ISSUE THREAD

**Issue by sadwizard** [HiDeoo/intro.js-react#2]
i am importing files and getting error "Module not found: Error: Can't resolve 'intro.js' in"

**Comment by HiDeoo** [comment]
`intro.js` is listed as a `peerDependencies ` and since [npm v3](https://github.com/npm/npm/releases/tag/v3.0.0):

> `peerDependencies` no longer cause anything to be implicitly installed. Instead, npm will now warn if a packages peerDependencies are missing, but it's up to the consumer of the module (i.e. you) to ensure the peers get installed / are included in package.json as direct dependencies or devDependencies of your package.

**Comment by JohnGoodman** [comment]
Hey, I'm getting this error after adding the package with yarn:

./node_modules/intro.js-react/lib/components/Hints/index.js
Module not found: Can't resolve 'intro.js' in '*************/node_modules/intro.js-react/lib/components/Hints'

Am I installing this incorrectly or missing something? Thanks.

**Comment by HiDeoo** [comment]
> Hey, I'm getting this error after adding the package with yarn:
> 
> ./node_modules/intro.js-react/lib/components/Hints/index.js
> Module not found: Can't resolve 'intro.js' in '*************/node_modules/intro.js-react/lib/components/Hints'
> 
> Am I installing this incorrectly or missing something? Thanks.

Did you also install `intro.js` too ? As mentioned above, it's on the consumer hand to ensure that it's installed.

**Comment by HiDeoo** [comment]
> I installed intro.js but it is still not working in Next.js

I tried to repro but didn't have any issue using this package with Next.js.

<img width="798" alt="Screenshot 2021-10-21 at 11 38 47" src="https://user-images.githubusercontent.com/494699/138252399-0cc24eb3-a38e-4ca6-b1dc-892f34a9bc4c.png">

I just created a new Next.js project using `yarn create next-app`, imported this package and `intro.js` default CSS and rendered some steps on the client-side.

If you can provide a codesandbox repro that would be great.

**Comment by alanvera48** [comment]
Hi @HiDeoo did you make it works on next js?
