### ISSUE TITLE
Fails with one item in a "steps" list

### ISSUE THREAD

**Issue by Makave1i** [HiDeoo/intro.js-react#20]
Problem with this line https://github.com/HiDeoo/intro.js-react/blob/master/src/components/Steps/index.js#L251 when only one element included to a `steps`

To reproduce, remove one element in the sandbox https://codesandbox.io/embed/o2A4gwXE3?hidenavigation=1

**Comment by HiDeoo** [comment]
By quickly looking at this, it looks like this is an `intro.js` issue and specifically related to https://github.com/usablica/intro.js/pull/685.

It looks like these 3 specific calls are not undefined type-guarded while all the other ones above & below are:

https://github.com/usablica/intro.js/blob/b46bbcd8af46be2ae3b43aba850334b12ff03cdb/intro.js#L1367-L1369
