### ISSUE TITLE
Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by laibao101** [HiDeoo/intro.js-react#24]
#20 i have this problem too. 
intro.js@2.9.3
intro.js-react@0.2.0

i find this problem already in the issue list, seems it was resolved, but i have this problem today

here is the error in console:
![image](https://user-images.githubusercontent.com/17879221/54113967-55c50f00-4424-11e9-8b17-dff3d2021a49.png)

and my code is:
![image](https://user-images.githubusercontent.com/17879221/54114022-71c8b080-4424-11e9-90b5-93692b949bb3.png)

**Comment by HiDeoo** [comment]
This seems indeed related to #20.

> seems it was resolved

How did you verify this? By quickly looking at the current intro.js code, the code throwing at you is still not undefined type-guarded 

https://github.com/usablica/intro.js/blob/b46bbcd8af46be2ae3b43aba850334b12ff03cdb/intro.js#L1367-L1369

It looks like the fix should be in intro.js altho I'm not even sure the library is still maintained from the commit list / pending PR amount.

**Comment by laibao101** [comment]
https://github.com/usablica/intro.js/pull/236

i also look the problem up in the issue list in intro.js

this 236 PR seems fix issue with single-step pages

**Comment by HiDeoo** [comment]
The issue seems to fix the "Done" label not shown on pages with a single
data-step, I don't think this is related to your issue.

**Comment by laibao101** [comment]
OK，thanks, get it.  it looks like i should find another way to avoid this problem.

**Comment by curiousPup** [comment]
please share if you have found a solution yet

**Comment by fritx** [comment]
I use multiple <Steps> in one page, every time the other Steps get enabled, it throws the Error and lead to a page reload.

I even tried adding key prop or wrap them into a `{enabled && (<Steps />)}` but without success

```js
<Steps
  enabled={stepsEnabledFor1}
  steps={stepsFor1}
  initialStep={initialStep}
  onExit={handleExitFor1}
/>
<Steps
  enabled={stepsEnabledFor2}
  steps={stepsFor2}
  initialStep={initialStep}
  onExit={handleExitFor2}
/>
```

**Comment by coderliush** [comment]
> please share if you have found a solution yet

single-step will get the error, so you can set multiple-step and close the intro In the next event. just list this:
```js
const steps = [
    {
        element: '.a',
        intro: 'this is a true step',
    },
    {
        element: '.b',
        intro: 'just a placeholder',
    },
]
<Steps
    steps={steps}
    enabled={enabled}
    options={{
        hidePrev: true,
        nextLabel: 'done'
     }}
/>
```
