### ISSUE TITLE
Isomorphic support?

### ISSUE THREAD

**Issue by FMGordillo** [HiDeoo/intro.js-react#25]
Working with **Next.js** i've come across with this error:

```
document is not defined

ReferenceError: document is not defined
    at introJs (...\node_modules\intro.js\intro.js:2330:30)
```

As I can't access directly to the DOM (with things like `.querySelector()`) it's like a dead end.
Does anyone know how to integrate it with SSR, or if there's something similar for those cases?

**Comment by HiDeoo** [comment]
Did you try a dynamic import with SSR disabled for this specific import?

https://github.com/zeit/next.js/#with-no-ssr

**Comment by FMGordillo** [comment]
**OMG** I've never seen that section, so sorry, bad me

**Comment by alanvera48** [comment]
Hi @FMGordillo  did you get it? How did you import the library?

**Comment by FMGordillo** [comment]
Hey!
Most probably if I try again this should work, but this issue is Stale at this point

Thank you for reaching out!

**Comment by alanvera48** [comment]
@FMGordillo for real? because i am trying to use it in next js and does not work. Could you please send me how did you import? or help me with that?
