### ISSUE TITLE
If class does not exist,  How to skip step in react js ?

### ISSUE THREAD

**Issue by jaimin-nimble** [HiDeoo/intro.js-react#26]
i want to skip the step when element is not exist. but if element exist so my step should not be skipped. 

I want to achieve this scenario.
Please help me out

Thanks in advance

**Comment by HiDeoo** [comment]
I guess you could use `onAfterChange`, check if the element exists in this step and if not, use immediately the [intro.js API](https://github.com/HiDeoo/intro.js-react#introjs-api) with something like `this.refName.introJs.nextStep()` (I don't remember the exact API call but I guess you'll find that easily in their documentation).

**Comment by jaimin-nimble** [comment]
**Thank you very much !** 
You saved my time

**Comment by onursabitsalman** [comment]
> **Thank you very much !**
> You saved my time

Hi, could you share your code for solve this problem?

**Comment by bronsonavila** [comment]
@onursabitsalman Might be a few years too late for you, but hopefully this helps someone else. Here's an example:

```javascript
const steps = [
  { element: '.selector1', intro: 'step 1' },
  { element: '.selector2', intro: 'step 2' },
  { element: '.selector3', intro: 'step 3' }
]

const stepsRef = useRef()

const onAfterChange = newStepIndex => {
  if (newStepIndex === 1) {
    const element = document.querySelector('.selector2')

    if (!element) stepsRef.current.introJs.nextStep()
  }
}

<Steps onAfterChange={onAfterChange} ref={stepsRef} steps={steps} />
```

This will force IntroJS to skip `'step 2'` (being index `1` of `steps`) if `'.selector2'` is not found on the page.
