### ISSUE TITLE
If class does not exist, how to don't show this step in react js ?

### ISSUE THREAD

**Issue by onursabitsalman** [HiDeoo/intro.js-react#31]
Firstly, I know there is existing related issue but there is no solution. If class does not exist, how to don't show this step in react js ?

**Comment by HiDeoo** [comment]
The solution I described in [this message](https://github.com/HiDeoo/intro.js-react/issues/26#issuecomment-476537997) should work.

Every time the current step is modified in Intro.js, you can use the `onAfterChange` callback available with this wrapper (described [here](https://github.com/HiDeoo/intro.js-react/tree/a8e8616d56e53422ed17d084763ec158ceb00e58#props)) as it'll be called at every step change. You can use this as an opportunity to check if the element/class exist, if it does not, you can manually change the step using the Intro.js API that you can [access using a ref](https://github.com/HiDeoo/intro.js-react/tree/a8e8616d56e53422ed17d084763ec158ceb00e58#introjs-api).
