### ISSUE TITLE
onExit gets called even before the steps load

### ISSUE THREAD

**Issue by curiousPup** [HiDeoo/intro.js-react#32]

**Comment by Vinxtime** [comment]
Getting the same issue, cannot use the lib

**Comment by HiDeoo** [comment]
I can't manage to repro using the [codesandbox.io example](https://codesandbox.io/embed/o2A4gwXE3?hidenavigation=1) in the README, `onExit` only gets called when exiting.

Feel free to re-open if you can provide a small repro.
