### ISSUE TITLE
Error when using keyboard to navigate through the steps. (Uncaught TypeError: Cannot read property 'element' of undefined. )

### ISSUE THREAD

**Issue by MSPShaun** [HiDeoo/intro.js-react#33]
I have found that an error gets called anytime i navigate through the steps of a tutorial using a keyboard. The error can be triggered by 
1. Starting a tutorial
2. Using the right arrow key to go through **all** the steps
3. On the last step, try to use the right arrow key again. This will cause the error.
`Uncaught TypeError: Cannot read property 'element' of undefined
    at IntroJs._nextStep (intro.js?479f:425)
    at IntroJs._onKeyDown (intro.js?479f:320)
    at handler (intro.js?479f:1576)`

It seems as though there is a counter that is still getting triggered by the keyboard event even though there isn't any steps remaining. this error doesn't exist when using the main Intro.js library (Non-react),  instead it would close the tutorial.

This error can easily be reproduced using the sandbox demo given in this repository: 
https://codesandbox.io/embed/o2A4gwXE3?hidenavigation=1

**Comment by HiDeoo** [comment]
This is actually an issue in Intro.js itself (cf. https://github.com/usablica/intro.js/issues/951 for a similar issue) 

The report summarize the issue but it boils down to [these lines](https://github.com/usablica/intro.js/blob/d3059b0edd8ca7d020fe9d25ed6835f694ebae6f/intro.js#L424-L426) when using the [`introJs.onbeforechange()` API](https://introjs.com/docs/intro/api/#introjsonbeforechangeprovidedcallback) (which is always the case of this library) and Intro.js not checking step bounds before trying to call this callback.

Considering the number of pending PRs for Intro.js (if still maintained), you may need to fork the library yourself or patch it somehow.
