### ISSUE TITLE
Hide prev/next button and remove 

### ISSUE THREAD

**Issue by jacobwod** [HiDeoo/intro.js-react#35]
# The problem
I think that the last step of the guide should look a bit different than it currently does. What I try to achieve is:
1. hide the previous and next buttons, and
2. remove `.introjs-skipbutton` class from the Done button, so it isn't grayed out (as Skip button is)

The last step looks like this in DOM:
![bild](https://user-images.githubusercontent.com/110222/73642758-90561c80-4672-11ea-9641-3cbfea8a89b2.png)

Which renders this:
![bild](https://user-images.githubusercontent.com/110222/73642792-a19f2900-4672-11ea-99fb-18aa2e28e4f8.png)

# Proposed solution
What I want to show is this (perhaps centering the Done button would be even better):
![bild](https://user-images.githubusercontent.com/110222/73643782-656cc800-4674-11ea-9692-30e6fa465bbf.png)

It's easy enough to determine which step is the last. I can hook into `onBeforeChange()` and do a quick check:
```javascript
      <Steps
        [...]
        ref={steps => (localSteps = steps)}
        onBeforeChange={nextStepIndex => {
          if (nextStepIndex) {
            localSteps.updateStepElement(nextStepIndex);
          }
          if (nextStepIndex === localSteps?.props.steps.length - 1) {
            console.log("This is the last step!");
            // Now it's time to hide prev/next and change CSS class of Done button. But how?
          }
        }}
      />
```

I am aware of `hidePrev` and `hideNext` options for Intro.JS. But, **I can't just send new `options` to `<Steps />`, so how can this be done otherwise?**

**Comment by jacobwod** [comment]
I've found a way to fix styling of Done button as well as hide the prev/next button on the last slide. It definitevly counts as a hack, so please let me know when a more appropiate way of hiding prev/next buttons on last slide will be available and I'll be happy to change my code. Anyway, here is the current solution:

```javascript
          // Create a ref that holds the actual steps (I get them from this.state in my code)
          ref={steps => (this.localSteps = steps)}
          onBeforeChange={nextStepIndex => {
            // Ensure that we always use the updated list of steps, necessary for dynamic elements
            if (nextStepIndex) {
              this.localSteps.updateStepElement(nextStepIndex);
            }
          }}
          onAfterChange={nextStepIndex => {
            // TODO: When https://github.com/HiDeoo/intro.js-react/issues/35 is solved, we can remove this nasty hack.
            // It should be easier to hide prev/next buttons, but this works for now.
            if (nextStepIndex === this.localSteps?.props.steps.length - 1) {
              document
                .querySelector(".introjs-donebutton")
                .classList.remove("introjs-skipbutton");
              document.querySelector(".introjs-prevbutton").style.display =
                "none";
              document.querySelector(".introjs-nextbutton").style.display =
                "none";
              document.querySelector(".introjs-bullets").style.display = "none";
            }
          }}
```

**Comment by HiDeoo** [comment]
Sadly, your workaround is pretty much the way to do it at the moment.

I went into a bit more details in this [old issue](https://github.com/HiDeoo/intro.js-react/issues/17) but basically, this is not supported in Intro.js itself at the moment (cf. https://github.com/usablica/intro.js/issues/703 & https://github.com/usablica/intro.js/issues/640)
