### ISSUE TITLE
Cannot read property ""'updateStepElement'"" of undefined introjs

### ISSUE THREAD

**Issue by mrinmoymsarkar** [HiDeoo/intro.js-react#36]
To update the Dynamic elements as mentioned in the docs I tried using it in following manner:

To do that, you can use the updateStepElement() API and pass to it the index of the step to update:

<Steps
  enabled={stepsEnabled}
  steps={steps}
  ref={steps => (this.steps = steps)}
/>
onBeforeChange = nextStepIndex => {
  if (nextStepIndex === 4) {
    this.steps.updateStepElement(nextStepIndex);
  }
}

I keep receiving this error:

Uncaught TypeError: Cannot read property 'updateStepElement' of undefined

Can you please give a proper guide to how to use this? Have been stuck for a few days now

**Comment by HiDeoo** [comment]
I made a small example available [here](https://codesandbox.io/s/introjs-react-dynamic-element-example-bk6xj?file=/index.js) altho from the `Cannot read property 'updateStepElement' of undefined` error, it looks like your React ref to the `<Steps />` component is undefined so unrelated to this library I guess.
