### ISSUE TITLE
If onAfterChange is used to check dynamically and then go to next step then the back button does not work.

### ISSUE THREAD

**Issue by mrinmoymsarkar** [HiDeoo/intro.js-react#37]
I guess you could use `onAfterChange`, check if the element exists in this step and if not, use immediately the [intro.js API](https://github.com/HiDeoo/intro.js-react#introjs-api) with something like `this.refName.introJs.nextStep()` (I don't remember the exact API call but I guess you'll find that easily in their documentation).

_Originally posted by @HiDeoo in https://github.com/HiDeoo/intro.js-react/issues/26#issuecomment-476537997_

I used this and go it to skip the step if the element does not exist but then back button does not work.

Here is the code https://codesandbox.io/s/introjs-react-options-b3meg

**Comment by HiDeoo** [comment]
I think it may only be a logic problem:

1. When hitting `onAfterChange` for the first time and if your condition `currentStep  && element &&element.classList[0]=== "introjsFloatingElement"` is `true`, you'll advance to the next step.
2. If you hit the back button, `onAfterChange` is hit again but the condition is still `true` so your code you'll advance again immediately to the next step making it looks like you didn't do anything.

If you log `currentStep` in `onAfterChange` you'll see 2 logs when hitting the back button, the first one being `1` and immediately `2` after that.

You may need to include some state here to accommodate with this case.

**Comment by bronsonavila** [comment]
Ran into this same problem and didn't find the answer above to be sufficiently informative enough. Here's an example of the code that helped me solve this problem on my end:

```javascript
const steps = [
  { element: '.selector1', intro: 'step 1' },
  { element: '.selector2', intro: 'step 2' },
  { element: '.selector3', intro: 'step 3' }
]

const previousStepRef = useRef()

const onAfterChange = newStepIndex => {
  if (newStepIndex === 1) {
    const element = document.querySelector('#view-document')

    if (!element) {
      previousStepRef.current === 0 ? stepsRef.current.introJs.nextStep() : stepsRef.current.introJs.previousStep()
    }
  }

  previousStepRef.current = newStepIndex
}

<Steps onAfterChange={onAfterChange} ref={stepsRef} steps={steps} />
```

This allowed me to move back and forth between step 1 and step 3 while skipping step 2. It's important to note that you need to use a `ref` – don't track your previous step in `state`.
