### ISSUE TITLE
How to goToStep?

### ISSUE THREAD

**Issue by capsule5** [HiDeoo/intro.js-react#38]
Is it possible to have acces to the following methods : https://introjs.com/docs/intro/api/#introjsgotostepstep

**Comment by HiDeoo** [comment]
If you need to [use the Intro.js API](https://github.com/HiDeoo/intro.js-react#introjs-api), you can still get the Intro.js instance by using a ref on a `<Steps />` component and using `this.refName.introJs.goToStep()` for example.
