### ISSUE TITLE
How to call a function after the the skip button is clicked

### ISSUE THREAD

**Issue by fjuriolli** [HiDeoo/intro.js-react#40]
Is there an easy way for this?

**Comment by HiDeoo** [comment]
According to the [intro.js changelog](https://github.com/usablica/intro.js/blob/master/changelog.md), version `v2.9.0` added that kind of callback:

> Added `onskip` callback

If you're using an intro.js version supporting this feature, you can access the intro.js API using this React wrapper with [a ref](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs). This is documented in the README [here](https://github.com/HiDeoo/intro.js-react#introjs-api).

So this should be doable without any issue.
