### ISSUE TITLE
the intro props not support react elment ?

### ISSUE THREAD

**Issue by mabelyong** [HiDeoo/intro.js-react#41]
versions:
```json
"intro.js": "^2.9.3",
"intro.js-react": "^0.2.0",
```
use like this:
```javascript
const steps = [
    {
      element: '#__cash-flow__level a',
      position: 'right',
      highlightClass: 'aside-menu-hlight',
      intro: <div>hello world</div>,
    },
    {
      element: '#__cash-flow__pool a',
      position: 'right',
      highlightClass: 'aside-menu-hlight',
      intro: 'teeeeeeeeeeeeeest',
    }
]
```
but have a warning like this ==> Warning: Failed prop type: Invalid prop `steps[0].intro` of type `object` supplied to `Steps`, expected `string`.

**Comment by HiDeoo** [comment]
This was the expected behaviour in the original version. This was changed recently in a PR (https://github.com/HiDeoo/intro.js-react/commit/cfec1d081edc4220c338e0cc854eca8aaef8f400) adding support for elements.

**Comment by mabelyong** [comment]
> This was the expected behaviour in the original version. This was changed recently in a PR ([cfec1d0](https://github.com/HiDeoo/intro.js-react/commit/cfec1d081edc4220c338e0cc854eca8aaef8f400)) adding support for elements.

hi, already supported but forget release to the npm repo? the version still `^0.2.0` now~
