### ISSUE TITLE
close (x) button on tooltip is not available

### ISSUE THREAD

**Issue by rajesh2204** [HiDeoo/intro.js-react#42]
Hi HiDeoo,

The tooltip is not configurable to have a close button,Could you please help,

![image](https://user-images.githubusercontent.com/34715042/87876994-35826880-c9f9-11ea-9644-1afb789a12e3.png)

**Comment by HiDeoo** [comment]
This project is just a React wrapper for [Intro.js](https://introjs.com/). If this feature is not supported by [Intro.js](https://introjs.com/), it should be requested / implemented in their repo.
