### ISSUE TITLE
On Final step in the tooltip , possible to have restart button ? 

### ISSUE THREAD

**Issue by rajesh2204** [HiDeoo/intro.js-react#43]
Hi Team,

Is there any possible way to restart from first step once we reach last step ? 

on tooltip button like after Done, Restart ?

**Comment by HiDeoo** [comment]
I don't think this is a feature of [Intro.js](https://introjs.com/), maybe it could be requested over there, altho I assume you could get to something close to what you want using the [Intro.js API](https://introjs.com/docs/intro/api/) which you can access when using this React wrapper [with a reference](https://reactjs.org/docs/refs-and-the-dom.html) as described [in the documentation](https://github.com/HiDeoo/intro.js-react#introjs-api).
