### ISSUE TITLE
Step.intro unable support React.element props

### ISSUE THREAD

**Issue by jamgejun** [HiDeoo/intro.js-react#45]
the doc said step.intro enable support React.element props, but when i use this ability that can't take effect。

only way i can use like this:
![image](https://user-images.githubusercontent.com/27955731/89728636-42770280-da61-11ea-8a0b-9368cf944d51.png)

i wish i can use like this:
![image](https://user-images.githubusercontent.com/27955731/89728698-d8129200-da61-11ea-80b6-b8d73721b4c6.png)

i  think intro.js also can't support this.

**Comment by HiDeoo** [comment]
This has been added not so long in https://github.com/HiDeoo/intro.js-react/commit/cfec1d081edc4220c338e0cc854eca8aaef8f400 which is not yet released. Until then, if needed, you can directly use this commit or the master branch from this repo as a dependency.
