### ISSUE TITLE
Cannot re-enable intro if exited by clicking on the overlay layer

### ISSUE THREAD

**Issue by alinnawen** [HiDeoo/intro.js-react#46]
I am trying to control whether the intro is enable via props and react lifecycle 
e.g. setting enabled = {this.props.enabled && (this.prop.lastStep<stepCount)}

When trying to re-enable the intro via setting enable=true and lastStep=0

**[works]** when intro is exited via clicking the 'skip' button or if the intro exited on completion
**[doesnt work]** if intro is exited via clicking on the overlay layer

Is this expected? Anyway I can get it to work for both cases?

**Comment by HiDeoo** [comment]
You can take a look at [the example](https://codesandbox.io/embed/o2A4gwXE3?hidenavigation=1) linked in the README.

It includes a *Toggle Steps* button which enable the intro when clicking on it using a basic `setState` and that state is used in the `enabled` prop which I think is the exact example you're describing.

Clicking this button re-enable the intro if it was skipped or exited on completion and also if the intro was exited by clicking the overlay layer.

If not, feel free to re-open the issue with a repro in a codesandbox so we can take a look.
