### ISSUE TITLE
@types definition?

### ISSUE THREAD

**Issue by ufo2mstar** [HiDeoo/intro.js-react#48]
Any plans on adding a Typescript definition for this wrapper library?
Like the one for intro.js itself: https://libraries.io/npm/@types%2Fintro.js/3.0.0

**Comment by HiDeoo** [comment]
No short term plans so far but just added your suggestion to my todo list for when I have more time.

**Comment by ufo2mstar** [comment]
Thank you @HiDeoo , just using the plain js version for now
Have some CSS overlap issues on the edge of the screen, but not sure if they are an introjs issue or issue with this react port
Will just open another issue for you to look into, just in case
