### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by AnthonyLedru** [HiDeoo/intro.js-react#50]
Hi,
I just noticed the package now support React elements in intro step:
https://github.com/HiDeoo/intro.js-react/commit/cfec1d081edc4220c338e0cc854eca8aaef8f400

But it seems the NPM package v0.2.0 is not updated yet with this feature, could you please update it?

Thanks

**Comment by HiDeoo** [comment]
Thanks for the reminder, [`v0.3.0`](https://www.npmjs.com/package/intro.js-react/v/0.3.0) is now available on npm.
