### ISSUE TITLE
multi-page problem: when the page change, the element by className is not selected anymore

### ISSUE THREAD

**Issue by Abderrazzek** [HiDeoo/intro.js-react#51]
When I'm on the same page, it works but the problem is when I change the page:
I'm using react-router-dom:  history.push("/page") to change page: intro.js don't select the className anymore because the change of the dom content like the element is not seen by intro.js.

**Comment by HiDeoo** [comment]
Just made [a quick repro](https://codesandbox.io/s/introjs-react-router-push-vj1jc?file=/pages/Home.jsx) using `react-router-dom` and `history.push()` but I cannot repro the issue. On the home page, if you click on the *Go to Dashboard* button, it properly navigate to the `/dashboard` page using `history.push()` and trigger the intro.

Maybe this repro can help you figure out your issue or can you provide a CodeSandbox repro of your issue?

**Comment by Abderrazzek** [comment]
Thank you for this repro. But can you please create an intro which links directly all the pages(dashboard, home, about)? So that I can use all the pages at the same intro.
This was actually my problem: when I change to next page, it doesn't read the element class name and doesn't select it anymore.

**Comment by HiDeoo** [comment]
I'm not sure I follow but you can fork the linked codesandbox yourself and make something matching your use-case and repro-ing the issue.
