### ISSUE TITLE
location of intro js container

### ISSUE THREAD

**Issue by mehridaie** [HiDeoo/intro.js-react#52]
Hi, 
I have an issue with using intro.js-react library. 
Imagine this scenario :
1- a page with a card (card A)  inside it.
2-when click on card A another card (SecondCard) will be open beside card A, so the width of card A become 50%,
3- using introjs for card A and SecondCard:  SecondCard's first step doesn't locate where it should.
in short: with update location of elements intro.js-react doesn't update.

**Comment by HiDeoo** [comment]
You can check the [*dynamic elements* example](https://github.com/HiDeoo/intro.js-react#dynamic-elements) from the README to see how to properly use a step on your second card which is dynamically added after a click event.

**Comment by mehridaie** [comment]
I tested this solution too, it's not working. because I have this issue
with the first item of my steps. I got this error and couldn't fix it.
(steps.updateStepElement
is not a function)
but it will be great if you can see the functional component samples for
features of intro.js.

**Comment by HiDeoo** [comment]
Could you make a quick basic repro of the issue on https://codesandbox.io ?

**Comment by shamseen** [comment]
> but it will be great if you can see the functional component samples for features of intro.js.

@mehridaie I've converted some of the initial demo to functional components [here](https://codesandbox.io/s/introjs-react-example-forked-n8yjj?file=/App.js). Dynamic element is working!

 However there are a few bugs I can't figure out: first step is skipping and the step numbers aren't hiding.
