### ISSUE TITLE
"Done" button not showing on the last step

### ISSUE THREAD

**Issue by mikolus** [HiDeoo/intro.js-react#56]
In the last step, "Done" button is hidden.
Problem can be reproduced in the official example by updating intro.js and intro.js-react to the most recent versions:

https://codesandbox.io/s/introjs-react-example-forked-jhq7d

When I use intro.js in plain javascript, without the react wrapper, "Done" button appears as expected.

**Comment by mikolus** [comment]
I found a workaround - setting "skipLabel" option also makes the "Done" button to appear. Setting it to the default "×" character  will work.

**Comment by markdeitchell** [comment]
> I found a workaround - setting "skipLabel" option also makes the "Done" button to appear. Setting it to the default "×" character will work.

This solution didn't work for me. Any ideas?
https://codesandbox.io/s/introjs-react-example-forked-6b918

**Comment by HiDeoo** [comment]
I'm assuming this is related to [this issue](https://github.com/usablica/intro.js/issues/1093) and a behaviour change in Intro.js.

Adding `options={{ hideNext: false }}` to the `<Steps />` component in your codesandbox brings back the *Done* button.

**Comment by Raaj66** [comment]
> options={{ hideNext: false }}

Thank you. this is what is was exactly looking for

**Comment by sandeeprana191** [comment]
> I'm assuming this is related to [this issue](https://github.com/usablica/intro.js/issues/1093) and a behaviour change in Intro.js.
> 
> Adding `options={{ hideNext: false }}` to the `<Steps />` component in your codesandbox brings back the _Done_ button.

Thanks!

**Comment by Kalutu** [comment]
> > I'm assuming this is related to [this issue](https://github.com/usablica/intro.js/issues/1093) and a behaviour change in Intro.js.
> > Adding `options={{ hideNext: false }}` to the `<Steps />` component in your codesandbox brings back the _Done_ button.
> 
> Thanks!

I was having same issues. This worked for me. Thanks @sandeeprana191
