### ISSUE TITLE
use intro js in storybook 6

### ISSUE THREAD

**Issue by parisabrz** [HiDeoo/intro.js-react#59]
hi guys,
im using storybook in my app, when i open intro component in storybook, it show the intro box in wrong place, please help me im need it

**Comment by HiDeoo** [comment]
Position issues have been most of the time in the past related to [Intro.js](https://introjs.com/) directly and the React wrapper itself. 

If you could provide a [CodeSandbox](https://codesandbox.io/) or repo URL of a repro of the issue, I could take a look at it anw.
