### ISSUE TITLE
Wiring up to dynamic elements

### ISSUE THREAD

**Issue by jcarioti** [HiDeoo/intro.js-react#6]
I see that this wrapper should be able to handle dynamic DOM elements, but the instructions around this feature are vague and don't seem to be working for me. 

If I'm understanding properly, then this should be the onBeforeChange event handler passed to the <Steps /> component: 

```
onBeforeChange = nextStepIndex => {
  if (nextStepIndex === 4) {
    this.step.updateStepElement(nextStepIndex);
  }
}
```

The problem I'm having is that `this.step` is not defined as anything. The source code shows that `updateStepElement(nextStepIndex)` is defined as a member function of the `Steps` component, but I'm not sure how to access that function.

**Comment by HiDeoo** [comment]
You're totally right regarding the fact that you'll need to use `updateStepElement()` to update the element associated to the step when it's available after dynamically adding it.

In the example, `this.step` is just a [reference](https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-class-component) to the `Step` component instance, so when declaring it, you would use something like:

```jsx
<Steps
  enabled={stepsEnabled}
  steps={steps}
  ref={steps => (this.steps = steps)}
/>
```

In this case, the `ref` callback would receives the mounted instance of the `Steps` component and save a reference to it in `this.steps`. Then, you'll be able to use `this.step.updateStepElement(nextStepIndex)`.

There is a reference example in the README in the [Intro.js API section](https://github.com/HiDeoo/intro.js-react#introjs-api) but I think you raise a good point and I should add it too to the [dynamic elements section](https://github.com/HiDeoo/intro.js-react#dynamic-elements) of the README.

I hope the answer is clear enough, if not, don't hesitate to re-open this issue.

**Comment by jcarioti** [comment]
Thank you! I actually figured this out and was typing out the solution when you responded. I think it would be a good idea to include the reference callback snippet on the readme page.
