### ISSUE TITLE
Dependency upgrades

### ISSUE THREAD

**Issue by Ckrill** [HiDeoo/intro.js-react#64]
Do you have plans to upgrade the peerDependencies `react` and `intro.js` in packages.json?

I would like to get rid of these warnings when running my project:
```
warning " > intro.js-react@0.4.0" has incorrect peer dependency "intro.js@^2.5.0".
warning " > intro.js-react@0.4.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-alpha".
```

Cheers

**Comment by HiDeoo** [comment]
Thanks for pointing this. I just updated the peer dependencies to avoid this warning.

https://github.com/HiDeoo/intro.js-react/blob/49c76fb8e74aa447d3ada978ac45f4bf9f2e7f12/package.json#L50-L53

This should be included in the next release.

**Comment by ntextreme3** [comment]
> This should be included in the next release.

any ETA on the next release?

**Comment by HiDeoo** [comment]
> > This should be included in the next release.
> 
> any ETA on the next release?

Just publish v0.5.0 that [contains the change](https://github.com/HiDeoo/intro.js-react/blob/master/CHANGELOG.md#050).
