### ISSUE TITLE
one first time init  run  twice

### ISSUE THREAD

**Issue by chenxu-javascript** [HiDeoo/intro.js-react#66]
![image](https://user-images.githubusercontent.com/16332458/126644513-a160fd3e-71b1-40ff-ba09-698924c7f1ef.png)
![image](https://user-images.githubusercontent.com/16332458/126644539-76fd35be-1a30-4d72-86aa-50175d389a79.png)

**Comment by HiDeoo** [comment]
This is a workaround [for various issues](https://github.com/usablica/intro.js/issues/465) using [the documented way](https://introjs.com/docs/intro/api#introjsgotostepstep) to start a tour from a specific step:

```js
introJs().goToStep(2).start(); //starts introduction from step 2
```
