### ISSUE TITLE
intro.js-react not working in Next.js

### ISSUE THREAD

**Issue by joshuaolusayo** [HiDeoo/intro.js-react#72]
I'm getting an error. Cannot find module intro.js

**Comment by HiDeoo** [comment]
You may be hitting [this issue](https://github.com/HiDeoo/intro.js-react/issues/2). `intro.js` is listed as a peerDependencies and since npm v3 these are not implicitly installed.

If it's related to another issue, feel free to re-open and include a codesandbox repro if possible.
