### ISSUE TITLE
showStepNumbers option to show  steps number in a red circle not working

### ISSUE THREAD

**Issue by ahoubouby** [HiDeoo/intro.js-react#78]
i'm using intorjs version 4.3.0 and intro.js-react  version 0.5.0. when I add option showStepNumbers, the red cicle is not showing.
in my code i use options={{
          showStepNumbers:true,
          showBullets: true
        }}
 FYI, this has worked in the older version: 3.0.1

**Comment by rajat-jain-au5** [comment]
I have same problem with showStepNumbers.please give  solution

**Comment by ahoubouby** [comment]
the problem is related to intro.js so i will close the issue.

**Comment by andreynav** [comment]
@ahoubouby @rajat-jain-au5 do you found any solutions?
I have the same problem now - https://take.ms/3XbBV
