### ISSUE TITLE
0.6.0 broken

### ISSUE THREAD

**Issue by HaoboZ** [HiDeoo/intro.js-react#82]
Gets error ReferenceError: Element is not defined. Looks like its not checking for instanceOf correctly or something

**Comment by HiDeoo** [comment]
I cannot manager to repro this issue, here is [a CodeSandbox example](https://codesandbox.io/s/intro-js-react-0-6-0-demo-kmowzd?file=/src/App.js) of the 0.6.0 version without any issues. 

Feel free to re-open with a complete repro if needed.

**Comment by kimmy214** [comment]
same issue.

nextjs: 12.0.7
