### ISSUE TITLE
Intro js is not working in next js.

### ISSUE THREAD

**Issue by alanvera48** [HiDeoo/intro.js-react#83]
I am try to use intro js and intro js react in next js app but i does not work. I try to use like this https://codesandbox.io/s/bk6xj but it returns an error like Element is not defined

**Comment by blackge** [comment]
Same issue here.

**Comment by omridevk** [comment]
if you import it like this:
```
const Steps = dynamic(() => import('intro.js-react').then((mod) => mod.Steps), {
    ssr: false,
});
```
It should work

**Comment by HiDeoo** [comment]
> ```js
> const Steps = dynamic(() => import('intro.js-react').then((mod) => mod.Steps), {
>     ssr: false,
> });
> ```

@omridevk is 100% correct. If needed, here is [a CodeSandbox example](https://codesandbox.io/s/intro-js-react-next-demo-21ps1y?file=/pages/index.js).
