### ISSUE TITLE
bind onxxxx property is Invalidation

### ISSUE THREAD

**Issue by Z1oftheKill** [HiDeoo/intro.js-react#87]
### Describe the bug

onClick or onXxxx is Invalidation  ,  cant execute!

### To Reproduce

` <Steps
        enabled={enabled}
        steps={[
          {
            element: ".my-sticky-sidebar",
            title: "1/6",
            intro: (
              <div
                onClick={() => {
                  console.log("");
                }}
              ></div>
            ),
          },
`

### Expected behavior

Hope to fix this bug

### How often does this bug happen?

Often

**Comment by HiDeoo** [comment]
Can you provide a repro of the issue, for example on https://codesandbox.io so I can see the exact error message, I'm not sure I understand the exact issue here?
