### ISSUE TITLE
"Unable to get property 'removeAttribute' of undefined or null reference" error when single step

### ISSUE THREAD

**Issue by baselrustum** [HiDeoo/intro.js-react#9]
I tried the demo on codesandbox. When I only want to tour using a single step, I get this error:
`Unable to get property 'removeAttribute' of undefined or null reference`

To repro, remove the following code from the demo:
```
,{
          element: '.world',
          intro: 'World step',
        },

```

**Comment by HiDeoo** [comment]
Hi,

This was actually a bug in `intro.js` which got fixed.

I updated the `intro.js` version in the sandbox and it should work fine for you now.

**Comment by baselrustum** [comment]
Thanks for confirming. Do you know which minimum version of intro.js that has the fix?

**Comment by HiDeoo** [comment]
The associated PR is [this one](https://github.com/usablica/intro.js/pull/685) and the fix is available since `intro.js` v2.6.0.
