### ISSUE TITLE
Asking for a minor relesase

### ISSUE THREAD

**Issue by nikitavik** [HiDeoo/intro.js-react#95]
### Is your feature request related to a problem?

Am so sorry to disturbing you with such a small issue, but, I think that type mismatch was pretty critical so I am asking you to do a minor release as soon as possible. Thank you.

### Describe the solution you'd like

Looking forward to 0.7.1 🥲

**Comment by HiDeoo** [comment]
I am planning to publish a new version including your fix as soon as I get home, which should be roughly in 3-4 ish hours.

I'll make sure to ping this issue as soon as it's up.

**Comment by HiDeoo** [comment]
> Looking forward to 0.7.1 🥲

Thanks for your patience, intro.js-react `v0.7.1` has been published on the npm registry.
